### ISSUE TITLE
Géocodage csv incomplet avec les larges fichiers

### ISSUE THREAD

**Issue by j-saur** [BaseAdresseNationale/api-geocode#14]
#### Fonctionement attendu : 

1. upload du fichier csv

2. selection des colonnes cibles
3. recuperation du fichier.geocoded.csv avec les colonnes résultats remplis 

#### Fonctionement observé : 

1. upload du fichier csv
2. selection des colonnes cibles
3. recuperation du fichier.geocoded.csv avec les colonnes résultats remplis **partiellement**

#### Exemple de retours utilisateur sur le géocodage incomplet : 

 - _parfois 3600 lignes géocodées, parfois 7200 alors que mon fichier initial en a 67331_

 - _mon fichier CSV en entrée fait environ 45 800 lignes. Et le géocodeur CSV ne me ressort en fin de traitement un géocodage sur 29 000 résultats._
 - _Le géocodeur ne traite que les 200 premières lignes._

**Comment by jdesboeufs** [comment]
L'implémentation actuelle fait que le fichier est envoyé puis géocodé et transmis à la volée. Donc si on arrive pas à géocoder une portion (on travaille par paquet de 100), on s'arrête là.

Les corrections apportées aujourd'hui en production permettent :
- de réduire les rejets de portions géocodées (nettoyage préalable)
- de faire 2 essais additionnels en cas d'erreur liée à la disponibilité de l'infrastructure

Nous travaillons à améliorer encore le processus, qui était un peu à l'abandon ces dernières années.
