### ISSUE TITLE
Limite de taille affichée sur les fichiers de géocodage CSV

### ISSUE THREAD

**Issue by pachevalier** [BaseAdresseNationale/api-geocode#16]
Dans la documentation, il y a une différence entre la limite affichée de taille de fichier pour le géocodage (50Mo) et le géocodage inversé (6Mo). Est-ce que c'est un problème de mise à jour de la doc où est-ce qu'il y a vraiment une différence entre géocodage et le géocodage inversé ?

**Comment by jdesboeufs** [comment]
Il y a bien une différence.
La limite à 50 Mo est liée aux possibilités de ce dépôt qui ne couvre pas le géocodage inverse à ce stade.
Addok seul supporte mal les gros fichiers.

À suivre, mais en attendant je ferme.
