### ISSUE TITLE
Ligne manquante lors de la recherche via CSV

### ISSUE THREAD

**Issue by steven62f** [BaseAdresseNationale/api-geocode#19]
Bonjour,

J'utilise l'API pour géolocaliser des adresses en envoyant des fichiers CSV.
J'ai constaté lors de mes tests que, parfois, le fichier CSV de retour est tronqué.
Par exemple, sur un fichier contenant plus de 700 lignes, le fichier de retour n'en contient que 600.
Mais le plus étrange, c'est que si j'essaye d'envoyer la/les lignes qui semblent poser problème en petit lot, ça passe sans problème.

Je ne parviens pas à comprendre ce qui pose problème et pourquoi, dans ce cas précis, l'API ne renvoie que les 600 premières lignes.

J'ai mis le fichier CSV concerné en pièce jointe.
[step 3.zip](https://github.com/etalab/adresse.data.gouv.fr/files/6868722/step.3.zip)

**Comment by jdesboeufs** [comment]
Doublon de #14 
On est dessus. À suivre.
