### ISSUE TITLE
Incorrect csv windows-1252 encoding 

### ISSUE THREAD

**Issue by mpipet** [BaseAdresseNationale/api-geocode#5]
When providing utf-8 csv file for batch geocoding, the returned file is sometimes wrongly encoded as
windows-1252.

It seems, it happens when at least one accentuated char is in the provided file.
In fact, after some investigation, jschardet-french library fail to detect correctly encoding of the provided buffer.

Being able to force output encoding thrue http headers would be nice.

**Comment by jdesboeufs** [comment]
`jdschardet-french` has been replaced by original `jschardet`.
Feel free to re-open this issue if the issue remains.

Sorry for the delay.
